### ISSUE TITLE
When the bucket region is eu-west-1 or ireland, it silently fails

### ISSUE THREAD

**Issue by vysakh0** [CargoSense/ex_aws#103]
I'm using `ex_aws` along with `arc`. I had no errors when uploading the image, but the image was not there in `s3` bucket. So, I tried to reproduce this in a new project and got this error (thankfully I didn't have `Poison` by default)

```
ex(2)> Exapi.Avatar.store a
** (EXIT from #PID<0.262.0>) an exception was raised:
    ** (UndefinedFunctionError) undefined function: Poison.decode/1 (module Poison is not available)
        Poison.decode("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'</Message><Region>eu-west-1</Region><RequestId>B002B839570F40F4</RequestId><HostId>+8j1EgIephErpZayQfxEC08nDhiOPx/zEAeAZTI5v8J4+nmAipu6q/UAIW08/+yQytbTMY8O6u4=</HostId></Error>")
        (ex_aws) lib/ex_aws/request.ex:55: ExAws.Request.client_error/2
        (ex_aws) lib/ex_aws/request.ex:40: ExAws.Request.request_and_retry/7
        (arc) lib/arc/storage/s3.ex:9: Arc.Storage.S3.put/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3

16:08:34.189 [error] Task #PID<0.265.0> started from #PID<0.262.0> terminating
** (UndefinedFunctionError) undefined function: Poison.decode/1 (module Poison is not available)
    Poison.decode("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'</Message><Region>eu-west-1</Region><RequestId>B002B839570F40F4</RequestId><HostId>+8j1EgIephErpZayQfxEC08nDhiOPx/zEAeAZTI5v8J4+nmAipu6q/UAIW08/+yQytbTMY8O6u4=</HostId></Error>")
    (ex_aws) lib/ex_aws/request.ex:55: ExAws.Request.client_error/2
    (ex_aws) lib/ex_aws/request.ex:40: ExAws.Request.request_and_retry/7
    (arc) lib/arc/storage/s3.ex:9: Arc.Storage.S3.put/3
    (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
    (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3
Function: #Function<2.40164739/0 in Arc.Actions.Store.async_put_version/3> 
```

This error is not caught. 

Setting this configuration has no effect
```
# config.exs

config :ex_aws,
  region: "eu-west-1"
  # ...
```

When trying to set the `s3` option like this
```
# config.exs

config :ex_aws,
 s3: [  region: "eu-west-1"]
  # ...
```
it throws this error

```
    ** (FunctionClauseError) no function clause matching in ExAws.S3.Request.url/3
        (cabs) lib/exapi/deps/ex_aws/lib/ex_aws/s3/request.ex:26: ExAws.S3.Request.url(%{access_key_id: "*************", http_client: ExAws.Request.HTTPoison, json_codec: Poison, region: "eu-west-1", secret_access_key: "**********************"}, "test-cab", "fuckthisshit/llll/original.png")
        (cabs) lib/exapi/deps/ex_aws/lib/ex_aws/s3/request.ex:13: ExAws.S3.Request.request/5
        (arc) lib/exapi/deps/arc/lib/arc/storage/s3.ex:9: Arc.Storage.S3.put/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3

Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> [error] Task #PID<0.2509.0> started from #PID<0.2506.0> terminating
** (FunctionClauseError) no function clause matching in ExAws.S3.Request.url/3
    (cabs) lib/exapi/deps/ex_aws/lib/ex_aws/s3/request.ex:26: ExAws.S3.Request.url(%{access_key_id: "************", http_client: ExAws.Request.HTTPoison, json_codec: Poison, region: "eu-west-1", secret_access_key: "*******************"}, "test-cab", "fuckthisshit/llll/original.png")
```

How do I get it working for a different region?  As a temporary work around I've created a bucket in `US standard` and it works now.

**Comment by benwilson512** [comment]
Hey, I'm working on improving this but basically the configurations aren't deep merged. Thus if you alter the :s3 key you need to supply all 3 configuration parameters.

```
config :ex_aws, :s3,
  scheme: "https://",
  host: "s3.amazonaws.com",
  region: "us-east-1"
```

**Comment by vysakh0** [comment]
@benwilson512 Thank you :+1:

**Comment by emilsoman** [comment]
Just got hit by this too. I was also assuming the configurations in `config.exs` would be deep merged over the defaults. Thanks for working on this.
