### ISSUE TITLE
Unable to upload files with non latin1 chars to S3

### ISSUE THREAD

**Issue by ericmj** [CargoSense/ex_aws#109]
The key signing is failing, I think because of the character encoding:

```
** (MatchError) no match of right hand side value: {:error, {:http_error, 403, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>[REMOVED]</AWSAccessKeyId><StringToSign>AWS4-HMAC-SHA256\n20160130T172731Z\n20160130/us-east-1/s3/aws4_request\n48579fd8a23c240c1ad2d8094100fa2750f742b3f1ff15710bf635c82955a320</StringToSign><SignatureProvided>811865a58f54f561fd535734d5de2c6b306c8c892f00d4e5ab2b0a447b0bdebe</SignatureProvided><StringToSignBytes>41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 31 36 30 31 33 30 54 31 37 32 37 33 31 5a 0a 32 30 31 36 30 31 33 30 2f 75 73 2d 65 61 73 74 2d 31 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 34 38 35 37 39 66 64 38 61 32 33 63 32 34 30 63 31 61 64 32 64 38 30 39 34 31 30 30 66 61 32 37 35 30 66 37 34 32 62 33 66 31 66 66 31 35 37 31 30 62 66 36 33 35 63 38 32 39 35 35 61 33 32 30</StringToSignBytes><CanonicalRequest>PUT\n/hexdocs.pm/eeb/0.1.3/eeb%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html\n\ncache-control:public, max-age=1800\ncontent-length:7336\ncontent-type:text/html\nhost:s3.amazonaws.com\nx-amz-acl:public-read\nx-amz-content-sha256:994c69f30572cacc01a705aeae3c61a21369b9964ba53cb87a0f5f6111c7eaa1\nx-amz-date:20160130T172731Z\n\ncache-control;content-length;content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date\n994c69f30572cacc01a705aeae3c61a21369b9964ba53cb87a0f5f6111c7eaa1</CanonicalRequest><CanonicalRequestBytes>50 55 54 0a 2f 68 65 78 64 6f 63 73 2e 70 6d 2f 65 65 62 2f 30 2e 31 2e 33 2f 65 65 62 25 45 34 25 42 44 25 42 46 25 45 37 25 39 34 25 41 38 25 45 38 25 41 46 25 42 34 25 45 36 25 39 38 25 38 45 2e 68 74 6d 6c 0a 0a 63 61 63 68 65 2d 63 6f 6e 74 72 6f 6c 3a 70 75 62 6c 69 63 2c 20 6d 61 78 2d 61 67 65 3d 31 38 30 30 0a 63 6f 6e 74 65 6e 74 2d 6c 65 6e 67 74 68 3a 37 33 33 36 0a 63 6f 6e 74 65 6e 74 2d 74 79 70 65 3a 74 65 78 74 2f 68 74 6d 6c 0a 68 6f 73 74 3a 73 33 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 0a 78 2d 61 6d 7a 2d 61 63 6c 3a 70 75 62 6c 69 63 2d 72 65 61 64 0a 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3a 39 39 34 63 36 39 66 33 30 35 37 32 63 61 63 63 30 31 61 37 30 35 61 65 61 65 33 63 36 31 61 32 31 33 36 39 62 39 39 36 34 62 61 35 33 63 62 38 37 61 30 66 35 66 36 31 31 31 63 37 65 61 61 31 0a 78 2d 61 6d 7a 2d 64 61 74 65 3a 32 30 31 36 30 31 33 30 54 31 37 32 37 33 31 5a 0a 0a 63 61 63 68 65 2d 63 6f 6e 74 72 6f 6c 3b 63 6f 6e 74 65 6e 74 2d 6c 65 6e 67 74 68 3b 63 6f 6e 74 65 6e 74 2d 74 79 70 65 3b 68 6f 73 74 3b 78 2d 61 6d 7a 2d 61 63 6c 3b 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3b 78 2d 61 6d 7a 2d 64 61 74 65 0a 39 39 34 63 36 39 66 33 30 35 37 32 63 61 63 63 30 31 61 37 30 35 61 65 61 65 33 63 36 31 61 32 31 33 36 39 62 39 39 36 34 62 61 35 33 63 62 38 37 61 30 66 35 66 36 31 31 31 63 37 65 61 61 31</CanonicalRequestBytes><RequestId>42FA3692E211CA7C</RequestId><HostId>ALQGxEfU79AXh7fJ5B0CdQUa+m29bfIHQjzYS2Z86cTMMw0vK9bGdg1KJTKsDMF0tZ1V9hrse9I=</HostId></Error>"}} Exception
2016-01-30 17:27:31.226949+00:00 app web.1 - - (ex_aws) lib/ex_aws/s3/impl.ex:310: ExAws.S3.Impl.put_object!/5
2016-01-30 17:27:31.226950+00:00 app web.1 - - (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
2016-01-30 17:27:31.226951+00:00 app web.1 - - (elixir) lib/enum.ex:604: Enum.each/2
2016-01-30 17:27:31.226952+00:00 app web.1 - - (hex_web) web/controllers/api/docs_controller.ex:156: HexWeb.API.DocsController.upload_docs/3
2016-01-30 17:27:31.226953+00:00 app web.1 - - (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
2016-01-30 17:27:31.226953+00:00 app web.1 - - (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

This is the file name: "eeb使用说明.html".

**Comment by benwilson512** [comment]
Fixed in 0.4.14
