### ISSUE TITLE
not_a_beam_file

### ISSUE THREAD

**Issue by ramhoj** [CargoSense/ex_aws#133]
```
$ mix release
==> Building release with MIX_ENV=dev.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
** (MatchError) no match of right hand side value: {:error, :beam_lib, {:not_a_beam_file, :"rel/pitch/lib/ex_aws-0.4.17/ebin/Elixir.ExAws.Kinesis.Impl.beam"}}
    lib/exrm/plugin.ex:97: anonymous fn/1 in ReleaseManager.Plugin.available_modules/1
    (elixir) lib/stream.ex:454: anonymous fn/4 in Stream.map/2
    (elixir) lib/enum.ex:2609: Enumerable.List.reduce/3
    (elixir) lib/stream.ex:1240: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:1391: Enum.reduce/3
    (elixir) lib/enum.ex:2170: Enum.uniq_by/2
    lib/exrm/plugin.ex:102: ReleaseManager.Plugin.available_modules/1
    lib/exrm/plugin.ex:83: ReleaseManager.Plugin.get_plugins/1
```

Elixir versions: 1.1.1, 1.2.3
OTP version: 18
ex_aws versions: 0.4.17, 0.4.10, 0.4.13, c8fb4ea744e94b8e131097153e9c111df349dc06
exrm version: 0.19.9

**Comment by ramhoj** [comment]
Error disappeared after removing the rel-folder.
