### ISSUE TITLE
[error] GenServer ExAws.Config.AuthCache terminating

### ISSUE THREAD

**Issue by hopewise** [CargoSense/ex_aws#151]
Hello,

When I call store at:

```
web/models/location.ex:

defmodule App.Location do
  @derive [ExAws.Dynamo.Encodable]
  defstruct [:lot, :lang, :user_id, :time]
end

web/controllers/location_controller.ex:

defmodule App.LocationController do
  use ExAws.Dynamo.Client
  alias ExAws.Dynamo
  def config_root do
      Application.get_all_env(:ex_aws)
  end
  def store do
    location = %App.Location{lot: 1.57, lang: 1.234, user_id: 23, time: 123847463882}
    # Save the user
    Dynamo.put_item("Locations", location)
  end
end
```

I get this error:

```
[error] GenServer ExAws.Config.AuthCache terminating
** (CaseClauseError) no case clause matching: {:error, %{__exception__: true, id: nil, reason: :enetunreach}}
    (ex_aws) lib/ex_aws/instance_meta.ex:5: ExAws.InstanceMeta.request/2
    (ex_aws) lib/ex_aws/instance_meta.ex:15: ExAws.InstanceMeta.security_credentials/1
    (ex_aws) lib/ex_aws/config/auth_cache.ex:37: ExAws.Config.AuthCache.refresh_config/2
    (ex_aws) lib/ex_aws/config/auth_cache.ex:27: ExAws.Config.AuthCache.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:refresh_config, %ExAws.Dynamo{config: %{access_key_id: [{:system, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}, :instance_role], host: {"$region", "dynamodb.$region.amazonaws.com"}, http_client: ExAws.Request.HTTPoison, json_codec: Poison, port: 80, region: "us-east-1", scheme: "https://", secret_access_key: [{:system, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}, :instance_role]}, service: :dynamodb}}
State: ExAws.Config.AuthCache
[error] GenServer #PID<0.538.0> terminating
** (stop) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %ExAws.Dynamo{config: %{access_key_id: [{:system, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}, :instance_role], host: {"$region", "dynamodb.$region.amazonaws.com"}, http_client: ExAws.Request.HTTPoison, json_codec: Poison, port: 80, region: "us-east-1", scheme: "https://", secret_access_key: [{:system, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}, :instance_role]}, service: :dynamodb}}, 5000)
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: {:error, %{__exception__: true, id: nil, reason: :enetunreach}}
            (ex_aws) lib/ex_aws/instance_meta.ex:5: ExAws.InstanceMeta.request/2
            (ex_aws) lib/ex_aws/instance_meta.ex:15: ExAws.InstanceMeta.security_credentials/1
            (ex_aws) lib/ex_aws/config/auth_cache.ex:37: ExAws.Config.AuthCache.refresh_config/2
            (ex_aws) lib/ex_aws/config/auth_cache.ex:27: ExAws.Config.AuthCache.handle_call/3
            (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:564: GenServer.call/3
    (ex_aws) lib/ex_aws/config.ex:59: ExAws.Config.retrieve_runtime_value/2
    (elixir) lib/stream.ex:454: anonymous fn/4 in Stream.map/2
    (elixir) lib/enum.ex:2744: Enumerable.List.reduce/3
    (elixir) lib/stream.ex:1247: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:790: Enum.find/3
    (ex_aws) lib/ex_aws/config.ex:45: anonymous fn/3 in ExAws.Config.retrieve_runtime_config/1
    (stdlib) lists.erl:1262: :lists.foldl/3
    (ex_aws) lib/ex_aws/config.ex:41: ExAws.Config.retrieve_runtime_config/1
    (ex_aws) lib/ex_aws/config.ex:18: ExAws.Config.build/2
    (ex_aws) lib/ex_aws/dynamo.ex:2: ExAws.Dynamo.put_item/2
    (app) web/channels/user_channel.ex:20: App.UserChannel.handle_in/3
    (phoenix) lib/phoenix/channel/server.ex:229: Phoenix.Channel.Server.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "new_annotation", payload: %{"body" => "aaa"}, ref: "2", topic: "users:0.50495536856846"}
State: %Phoenix.Socket{assigns: %{user_id: "0.50495536856846"}, channel: App.UserChannel, channel_pid: #PID<0.538.0>, endpoint: App.Endpoint, handler: App.UserSocket, id: nil, joined: true, pubsub_server: App.PubSub, ref: nil, serializer: Phoenix.Transports.WebSocketSerializer, topic: "users:0.50495536856846", transport: Phoenix.Transports.WebSocket, transport_name: :websocket, transport_pid: #PID<0.534.0>}
```

I have tried to get the keys successfully: 

    System.get_env("AWS_ACCESS_KEY_ID")
    System.get_env("AWS_SECRET_ACCESS_KEY")

I have put the config in dev.exs as:

```
config :ex_aws,
  access_key_id: [{:system, "xxxxxxxxxxxxxxxxx"}, :instance_role],
  secret_access_key: [{:system, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}, :instance_role],
  region: "us-east-2",
  dynamodb: [
    region: "us-east-1"
  ]
```

Also, here is my mix.exs file:

```
  def application do
    [mod: {App, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :ex_aws, :httpoison]]
  end
```

As for the above code, I have created the Locations table manually at aws console.

Also, if I try to use iex to create the db, I get erros:

```
iex(3)> alias ExAws.Dynamo
nil
iex(4)> Dynamo.create_table("Locations", "user_id", %{user_id: :integer}, 1, 1)
** (UndefinedFunctionError) undefined function ExAws.Dynamo.create_table/5 (module ExAws.Dynamo is not available)
    ExAws.Dynamo.create_table("Locations", "user_id", %{user_id: :integer}, 1, 1)
iex(4)>
```

Can you please help!

**Comment by hopewise** [comment]
my bad, I didn't put the app name in the config, just needed to add `:app`

    config :ex_aws, :app,
