### ISSUE TITLE
ExAws.S3.list_buckets Timeout and connection refused

### ISSUE THREAD

**Issue by aghosh47** [CargoSense/ex_aws#166]
Hi,
This is more of a question than a bug. I have an AWS S3 production access_key_id and secret_key,

This is my config.exs for the time being:

```
# This file is responsible for configuring your application
# and its dependencies with the aid of the Mix.Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.

use Mix.Config

# timebeing
System.put_env("AWS_ACCESS_KEY_ID", "aa")
System.put_env("AWS_SECRET_ACCESS_KEY", "bb")

# Configures the endpoint
config :expense, Expense.Endpoint,
  url: [host: "localhost"],
  root: Path.dirname(__DIR__),
  secret_key_base: "",
  render_errors: [accepts: ~w(html json)],
  pubsub: [name: Expense.PubSub,
           adapter: Phoenix.PubSub.PG2]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{Mix.env}.exs"

# Configure phoenix generators
config :phoenix, :generators,
  migration: true,
  binary_id: false

config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region: "us-east-1"

  config :ex_aws, :httpoison_opts,
    recv_timeout: 60_000,
    hackney: [recv_timeout: 60_000, pool: false]
```

And then I do an `ies -S mix` and I type in `ExAws.S3.list_buckets`, and I get a connection timeout followed by some connecrefused.

I have also tried , `config :ex_aws, :app`, `config :ex_aws, :expense,` but all yields the same result, and I would also like to know what is the significance of `:instance_role`

**Comment by benwilson512** [comment]
Can you gist the error you get?

**Comment by aghosh47** [comment]
iex(1)> ExAws.S3.list_buckets
[error] ExAws: HTTP ERROR: :connect_timeout
[error] ExAws: HTTP ERROR: :econnrefused
[error] ExAws: HTTP ERROR: :econnrefused
[error] ExAws: HTTP ERROR: :connect_timeout
[error] ExAws: HTTP ERROR: :connect_timeout
[error] ExAws: HTTP ERROR: :connect_timeout
[error] ExAws: HTTP ERROR: :connect_timeout
[error] ExAws: HTTP ERROR: :connect_timeout
[error] ExAws: HTTP ERROR: :connect_timeout

**Comment by benwilson512** [comment]
Ah interesting. Can you do
```
config :ex_aws, debug_requests: true
```
NOTE: The debug output WILL include your aws keys, make sure to remove before gisting.

**Comment by aghosh47** [comment]
```
iex(1)> ExAws.S3.list_buckets
[debug] Request URL: "https://s3-website-us-east-1.amazonaws.com/"
[debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=AxxxxQ/20160601/us-east-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=2bexx872"}, {"host", "s3-website-us-east-1.amazonaws.com"}, {"x-amz-date", "20160601T140310Z"}, {"content-length", 0}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996f55"}]
[debug] Request BODY: 
[error] ExAws: HTTP ERROR: :connect_timeout
```
I have trimmed down the credentials and signature

**Comment by benwilson512** [comment]
Yeah so for some reason the URL it's hitting is wrong. It's supposed to be `"https://s3.amazonaws.com/"` but instead it's `"https://s3-website-us-east-1.amazonaws.com/"` Do you have anything set in `dev.exs` ?

**Comment by benwilson512** [comment]
Also, what version of ExAws are you running?

**Comment by aghosh47** [comment]
no, I don't have any host set anywhere in the configs/
`{:ex_aws, "~> 0.4.10"}`

**Comment by benwilson512** [comment]
What value does it have in `mix.lock` ?

**Comment by aghosh47** [comment]
0.4.18

**Comment by benwilson512** [comment]
Well this is weird. Can you gist the config.exs and dev.exs files as you have them actually setup? It looks like you've edited them in the original gist.

**Comment by aghosh47** [comment]
the config.exs is actually like that, I don't know how to set system env variables. 
```
use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :expense, Expense.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin"]]

# Watch static and templates for browser reloading.
config :expense, Expense.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{web/views/.*(ex)$},
      ~r{web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development.
# Do not configure such in production as keeping
# and calculating stacktraces is usually expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :expense, Expense.Repo,
  adapter: Ecto.Adapters.MySQL,
  username: "root",
  password: "mysql",
  database: "expense_dev",
  hostname: "localhost",
  pool_size: 10
```
this is dev.exs

**Comment by aghosh47** [comment]
```
# This file is responsible for configuring your application
# and its dependencies with the aid of the Mix.Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.

use Mix.Config
System.put_env("AWS_ACCESS_KEY_ID", "A")
System.put_env("AWS_SECRET_ACCESS_KEY", "4")
# Configures the endpoint
config :expense, Expense.Endpoint,
  url: [host: "localhost"],
  root: Path.dirname(__DIR__),
  secret_key_base: "lQrt5SpdrCPawVb2a1tmXlMPQ96AoXt3UZKnRuW7kCHP+uJldmOMACt9tlzOmBvr",
  render_errors: [accepts: ~w(html json)],
  pubsub: [name: Expense.PubSub,
           adapter: Phoenix.PubSub.PG2]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{Mix.env}.exs"

# Configure phoenix generators
config :phoenix, :generators,
  migration: true,
  binary_id: false

config :ex_aws,
  debug_requests: true,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}],
  region: "us-east-1",
  host: %{
    "us-east-1" => "https://s3.amazonaws.com/"
  }

  config :ex_aws, :httpoison_opts,
    recv_timeout: 60_000,
    hackney: [recv_timeout: 60_000, pool: false]
```
config.exs

**Comment by benwilson512** [comment]
This is really weird, I'm unable to reproduce. Are you able to push up example code that exhibits this behaviour?

**Comment by benwilson512** [comment]
Were you able to see your AWS keys in the debug output by the way?

**Comment by benwilson512** [comment]
Hey real quick, can you change your mix.exs file to
```
{:ex_aws, "0.4.17"}
```

I want to make sure that latest version doesn't have a bug.

**Comment by benwilson512** [comment]
Alternatively, try `0.4.19` which I just pushed and has a number of bug fixes.

**Comment by aghosh47** [comment]
ok, I am trying it .

**Comment by aghosh47** [comment]
Hey. as to your first question, yes I was able to the ccorrect aws key with that debug option set.. and this  time I guess it works, I have a 403 error "The request signature we calculated does not match the signature you provided. Check your key and signing method"

**Comment by aghosh47** [comment]
ok I tried with another s3 account.. it worked.. thanks for the help..

**Comment by aghosh47** [comment]
@benwilson512 , Hi, I have been trying to integrate arc, arc_ecto and ex_aws, now I have a bucket which looks like `arn:aws:s3:::bucket-name/` and I was facing some issues, so I raised an issue in arc, and they said I should use only bucket-name as the bucket .. https://github.com/stavro/arc/issues/79

Now I have this problem: 

```
[debug] Request BODY: <<137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 100, 0, 0, 0, 100, 8, 6, 0, 0, 0, 112, 226, 149, 84, 0, 0, 0, 32, 99, 72, 82, 77, 0, 0, 122, 38, 0, 0, 128, 132, 0, ...>>
[error] Task #PID<0.1112.0> started from #PID<0.1099.0> terminating
** (CaseClauseError) no case clause matching: {:ok, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>bucket-name</Bucket><Endpoint>s3.amazonaws.com</Endpoint><RequestId>SOMEID</RequestId><HostId>dQ20Gh6GILlSfjbaT36KBRHV2AUafNctz/F8Eltdv9ePR1qYO+DHMlVQ4Os0MS5GmpZwpH+soVs=</HostId></Error>", headers: [{"x-amz-request-id", "EE110B56E69E1663"}, {"x-amz-id-2", "dQ20Gh6GILlSfjba"}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Mon, 13 Jun 2016 08:38:26 GMT"}, {"Connection", "close"}, {"Server", "AmazonS3"}], status_code: 301}}
    (ex_aws) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
    lib/arc/storage/s3.ex:14: Arc.Storage.S3.put/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<4.37961548/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
[error] Ranch protocol #PID<0.1099.0> (:cowboy_protocol) of listener Expense.Endpoint.HTTP terminated
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:ok, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>memento-is-dev</Bucket><Endpoint>s3.amazonaws.com</Endpoint><RequestId>SOMEID</RequestId><HostId>dQ20Gh6GILlSfjbaT36KBRHV2AUafNctz/F8Eltdv9ePR1qYO+DHMlVQ4Os0MS5GmpZwpH+soVs=</HostId></Error>", headers: [{"x-amz-request-id", "EE110B56E69E1663"}, {"x-amz-id-2", "dQ20Gh6GILlSfjba"}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Mon, 13 Jun 2016 08:38:26 GMT"}, {"Connection", "close"}, {"Server", "AmazonS3"}], status_code: 301}}
        (ex_aws) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
        lib/arc/storage/s3.ex:14: Arc.Storage.S3.put/3
        (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
plz help

**Comment by aghosh47** [comment]
ok I have found it.. the region was wrong.
