### ISSUE TITLE
HTTP Timeout?

### ISSUE THREAD

**Issue by alantonilopez** [CargoSense/ex_aws#204]
I'm getting a timeout trying to run an instance in EC2 from my home machine:

```
$ mix run
=INFO REPORT==== 20-Aug-2016::18:47:06 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application matchmaker: exited in: MatchMaker.start(:normal, [])
    ** (EXIT) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "SECRET"}, :instance_role], host: %{"ap-northeast-1" => "s3-ap-northeast-1.amazonaws.com", "ap-southeast-1" => "s3-ap-southeast-1.amazonaws.com", "ap-southeast-2" => "s3-ap-southeast-2.amazonaws.com", "eu-central-1" => "s3-eu-central-1.amazonaws.com", "eu-west-1" => "s3-eu-west-1.amazonaws.com", "sa-east-1" => "s3-sa-east-1.amazonaws.com", "us-east-1" => "s3.amazonaws.com", "us-west-1" => "s3-us-west-1.amazonaws.com", "us-west-2" => "s3-us-west-2.amazonaws.com"}, http_client: ExAws.Request.HTTPoison, json_codec: Poison, region: "us-east-1", scheme: "https://", secret_access_key: [{:system, "PASSWORD"}, :instance_role]}}, 5000)
        ** (EXIT) time out
```

Sometimes I'm getting this one:

```
$ mix run

=INFO REPORT==== 20-Aug-2016::18:48:07 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application matchmaker: exited in: MatchMaker.start(:normal, [])
    ** (EXIT) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "SECRET"}, :instance_role], host: %{"ap-northeast-1" => "s3-ap-northeast-1.amazonaws.com", "ap-southeast-1" => "s3-ap-southeast-1.amazonaws.com", "ap-southeast-2" => "s3-ap-southeast-2.amazonaws.com", "eu-central-1" => "s3-eu-central-1.amazonaws.com", "eu-west-1" => "s3-eu-west-1.amazonaws.com", "sa-east-1" => "s3-sa-east-1.amazonaws.com", "us-east-1" => "s3.amazonaws.com", "us-west-1" => "s3-us-west-1.amazonaws.com", "us-west-2" => "s3-us-west-2.amazonaws.com"}, http_client: ExAws.Request.HTTPoison, json_codec: Poison, region: "us-east-1", scheme: "https://", secret_access_key: [{:system, "PASSWORD"}, :instance_role]}}, 5000)
        ** (EXIT) an exception was raised:
            ** (CaseClauseError) no case clause matching: {:error, %{__exception__: true, id: nil, reason: :ehostunreach}}
                (ex_aws) lib/ex_aws/instance_meta.ex:5: ExAws.InstanceMeta.request/2
                (ex_aws) lib/ex_aws/instance_meta.ex:15: ExAws.InstanceMeta.security_credentials/1
                (ex_aws) lib/ex_aws/config/auth_cache.ex:37: ExAws.Config.AuthCache.refresh_config/2
                (ex_aws) lib/ex_aws/config/auth_cache.ex:27: ExAws.Config.AuthCache.handle_call/3
                (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
                (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
                (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Is there a way to check which HTTP request is being done internally?
Is there anyway to increase the HTTP timeout?

**Comment by benwilson512** [comment]
Is this happening on an EC2 instance? Or a local box?

Instance role auth is only available on EC2 instances with a configured role.

**Comment by alantonilopez** [comment]
This was happening because I was accessing the API outside of EC2. It seems that `http://169.254.169.254/latest/meta-data/` is only available within EC2.
