### ISSUE TITLE
Debug error response

### ISSUE THREAD

**Issue by alantonilopez** [CargoSense/ex_aws#205]
I'm trying to run a new instance from EC2 and I'm getting:

```bash
$ mix run

=INFO REPORT==== 20-Aug-2016::23:33:23 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application matchmaker: exited in: MatchMaker.start(:normal, [])
    ** (EXIT) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "SECRET"}, :instance_role], host: %{"ap-northeast-1" => "s3-ap-northeast-1.amazonaws.com", "ap-southeast-1" => "s3-ap-southeast-1.amazonaws.com", "ap-southeast-2" => "s3-ap-southeast-2.amazonaws.com", "eu-central-1" => "s3-eu-central-1.amazonaws.com", "eu-west-1" => "s3-eu-west-1.amazonaws.com", "sa-east-1" => "s3-sa-east-1.amazonaws.com", "us-east-1" => "s3.amazonaws.com", "us-west-1" => "s3-us-west-1.amazonaws.com", "us-west-2" => "s3-us-west-2.amazonaws.com"}, http_client: ExAws.Request.HTTPoison, json_codec: Poison, region: "us-east-1", scheme: "https://", secret_access_key: [{:system, "PASSWORD"}, :instance_role]}}, 5000)
        ** (EXIT) an exception was raised:
            ** (Poison.SyntaxError) Unexpected token: <
                (poison) lib/poison/parser.ex:56: Poison.Parser.parse!/2
                (poison) lib/poison.ex:83: Poison.decode!/2
                (ex_aws) lib/ex_aws/instance_meta.ex:16: ExAws.InstanceMeta.security_credentials/1
                (ex_aws) lib/ex_aws/config/auth_cache.ex:37: ExAws.Config.AuthCache.refresh_config/2
                (ex_aws) lib/ex_aws/config/auth_cache.ex:27: ExAws.Config.AuthCache.handle_call/3
                (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
                (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
                (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Is there a way to debug requests and responses to EC2?

**Comment by benwilson512** [comment]
There is not any built in way at the moment.

The hacky way is to edit the ExAws.Config.AuthCache file in your deps directory to include an `IO.inspect` call and `mix deps.compile ex_aws`.

I will look into error messages that display the result value.

As far as debugging what the issue is, the question from #204 applies here as well. Is this on an EC2 instance, and was that EC2 instance created with a role?

**Comment by alantonilopez** [comment]
Sorry for the late reply, this is what it shows:

```
<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>400 - Bad Request</title>\n </head>\n <body>\n  <h1>400 - Bad Request</h1>\n </body>\n</html>\n
```

**Comment by benwilson512** [comment]
Is this on an EC2 instance, and was that EC2 instance created with a role?

**Comment by alantonilopez** [comment]
No, it was the issue, however it makes a bit hard to test since we have to run our code on EC2. Is there a way to consume the API outside EC2?

**Comment by benwilson512** [comment]
Nope. It is only accessible from on a given EC2 instance. I'm not sure what you mean by "test". For any local work just use environment variable credentials.
