### ISSUE TITLE
Per Request Calls Failing

### ISSUE THREAD

**Issue by taylorbrooks** [CargoSense/ex_aws#206]
I'm trying to pass in my AWS config for each request my `config` looks like this:
````elixir
config = [
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role], 
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]
]
````

Then I try to make a request like:
````elixir
ExAws.SNS.list_topics |> ExAws.request(config)
````

and get this error:
````elixir
** (exit) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "REDACTED"}, :instance_role], host: {"$region", "sns.$region.amazonaws.com"}, http_client: ExAws.Request.HTTPoison, json_codec: Poison, port: 80, region: "us-east-1", scheme: "https://", secret_access_key: [{:system, "REDACTED"}, :instance_role]}}, 5000)
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function HTTPoison.request/5 is undefined (module HTTPoison is not available)
            HTTPoison.request(:get, "http://169.254.169.254/latest/meta-data//iam/security-credentials/", "", [], [recv_timeout: 30000, hackney: [recv_timeout: 30000]])
            (ex_aws) lib/ex_aws/request/httpoison.ex:35: ExAws.Request.HTTPoison.request/4
            (ex_aws) lib/ex_aws/instance_meta.ex:5: ExAws.InstanceMeta.request/2
            (ex_aws) lib/ex_aws/instance_meta.ex:15: ExAws.InstanceMeta.security_credentials/1
            (ex_aws) lib/ex_aws/config/auth_cache.ex:37: ExAws.Config.AuthCache.refresh_config/2
            (ex_aws) lib/ex_aws/config/auth_cache.ex:27: ExAws.Config.AuthCache.handle_call/3
            (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
[error] GenServer ExAws.Config.AuthCache terminating
** (UndefinedFunctionError) function HTTPoison.request/5 is undefined (module HTTPoison is not available)
    HTTPoison.request(:get, "http://169.254.169.254/latest/meta-data//iam/security-credentials/", "", [], [recv_timeout: 30000, hackney: [recv_timeout: 30000]])
    (ex_aws) lib/ex_aws/request/httpoison.ex:35: ExAws.Request.HTTPoison.request/4
    (ex_aws) lib/ex_aws/instance_meta.ex:5: ExAws.InstanceMeta.request/2
    (ex_aws) lib/ex_aws/instance_meta.ex:15: ExAws.InstanceMeta.security_credentials/1
    (ex_aws) lib/ex_aws/config/auth_cache.ex:37: ExAws.Config.AuthCache.refresh_config/2
    (ex_aws) lib/ex_aws/config/auth_cache.ex:27: ExAws.Config.AuthCache.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:refresh_config, %{access_key_id: [{:system, "REDACTED"}, :instance_role], host: {"$region", "sns.$region.amazonaws.com"}, http_client: ExAws.Request.HTTPoison, json_codec: Poison, port: 80, region: "us-east-1", scheme: "https://", secret_access_key: [{:system, "REDACTED"}, :instance_role]}}
State: ExAws.Config.AuthCache
    (elixir) lib/gen_server.ex:604: GenServer.call/3
    (ex_aws) lib/ex_aws/config.ex:60: ExAws.Config.retrieve_runtime_value/2
    (elixir) lib/stream.ex:490: anonymous fn/4 in Stream.map/2
    (elixir) lib/enum.ex:2842: Enumerable.List.reduce/3
    (elixir) lib/stream.ex:1284: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:839: Enum.find/3
    (ex_aws) lib/ex_aws/config.ex:48: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1
    (stdlib) lists.erl:1262: :lists.foldl/3
    (ex_aws) lib/ex_aws/config.ex:28: ExAws.Config.new/2
    (ex_aws) lib/ex_aws.ex:29: ExAws.request/2
````

Any ideas?

**Comment by benwilson512** [comment]
What version of ExAws do you have? I removed HTTPoison in favor of bare hackney but there was one commit in there where I'd forgotten to change one of the defaults.

**Comment by taylorbrooks** [comment]
1.0.0-beta0

**Comment by taylorbrooks** [comment]
Actually, that's what's specified in my `mix.exs` but here's my lock file:

````elixir
"ex_aws": {:hex, :ex_aws, "1.0.0-beta1", "7c101ce714190b91cc7033c4adc3eb593a5daea17cb4444e33e18d824dd0ee7f", [:mix], [{:httpoison, "~> 0.8", [hex: :httpoison, optional: true]}, {:jsx, "~> 2.5", [hex: :jsx, optional: true]}, {:poison    , "~> 1.2 or ~> 2.0", [hex: :poison, optional: true]}, {:sweet_xml, "~> 0.5", [hex: :sweet_xml, optional: true]}]}
````

**Comment by benwilson512** [comment]
Can you try this against master? I believe this is fixed there, will push another release if so.

**Comment by taylorbrooks** [comment]
How do I do that?

**Comment by taylorbrooks** [comment]
Yep works on master.

**Comment by benwilson512** [comment]
Cool, I'll push another release, thanks!
