### ISSUE TITLE
Compilation error creating an S3 client module

### ISSUE THREAD

**Issue by ttruongaa** [CargoSense/ex_aws#208]
I think I must be missing something obvious but I can't get this to work...following these [docs](https://hexdocs.pm/ex_aws/ExAws.S3.Client.html).

```elixir
#lib/brine/s3.ex
defmodule Brine.S3 do
	use ExAws.S3.Client, opt_app: :brine
end
```

```elixir
#config/config.exs
config :brine, :ex_aws,
  access_key_id: "**",
  secret_access_key: "**",
  s3: [region: "us-west-1"]
```

```elixir
#mix.exs

  def application do
    [mod: {Brine, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :ex_aws, :httpoison, :hackney, :poison]]
  end


  defp deps do
    [{:phoenix, "~> 1.2.0"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:guardian, "~> 0.12.0"},
     {:httpoison, "~> 0.7"},
     {:ex_aws, "~> 1.0.0-beta1"},
     {:poison, "~> 2.0"},
     {:hackney, "~> 1.6"},
     {:whatwasit, "~> 0.2"}
   ]
  end
```

When i run `iex -S mix` I get this error:
```
== Compilation error on file lib/brine/s3.ex ==
** (CompileError) lib/brine/s3.ex:2: module ExAws.S3.Client is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    lib/brine/s3.ex:2: Brine.S3 (module)
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Any help is much appreciated.

**Comment by benwilson512** [comment]
Hey there, you're looking the `0.5.0` docs but are using version `1.0.0-beta1`. You can find the `1.0.0-beta1` docs here: https://hexdocs.pm/ex_aws/1.0.0-beta1/ExAws.html

**Comment by MarsonV** [comment]
hi all, I have encountered the same problem, and I do not understand how to solve it. I would be glad of any help. The documentation on the version https://hexdocs.pm/ex_aws/1.0.0-beta1/ExAws.S3.html
in my mix.exs:
```
  def application do
    [mod: {Minion, []},
     applications: [:phoenix, ... :ex_aws, :httpoison, :poison]]
  end
...
  defp deps do
    [{:phoenix, "~> 1.2.1"},
...
     {:ex_aws, "~> 1.0.0-beta0"},
     {:poison, "~> 2.0"},
     {:httpoison, "~> 0.8"}]
  end
```
my config.exs:
```
config :minion, :ex_aws,
  access_key_id: "...",
  secret_access_key: "...",
  region: "us-east-1",
  s3: [
    scheme: "http://",
    host: "...",
    region: "us-east-1"
  ]
```
my s3.ex:
```
defmodule Minion.S3 do
  use ExAws.S3.Client, otp_app: :minion
end
```
when you try to start the server, I receive an error:
```
== Compilation error on file web/models/s3.ex ==
** (CompileError) web/models/s3.ex:2: module ExAws.S3.Client is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    web/models/s3.ex:2: Minion.S3 (module)
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```
