### ISSUE TITLE
Unable to make requests for services that use RestQuery

### ISSUE THREAD

**Issue by gaustin** [CargoSense/ex_aws#211]
I'm new to Elixir and probably just using this wrong. I'm trying to retrieve a list of my instances on EC2 and encountering an error.

This returns the expected XML payload, which proves to me my credentials are configured incorrectly.

```shell
iex(1)> ExAws.S3.list_buckets |> ExAws.request
```

When I try to use services that use RestQuery I get this:
```shell
iex(2)> ExAws.EC2.describe_instances |> ExAws.request
** (Protocol.UndefinedError) protocol ExAws.Operation not implemented for %ExAws.Operation.RestQuery{http_method: :get, params: %{"Action" => "DescribeInstances", "Version" => "2015-10-01"}, path: "/", service: :ec2}
    (ex_aws) lib/ex_aws/operation.ex:1: ExAws.Operation.impl_for!/1
    (ex_aws) lib/ex_aws/operation.ex:2: ExAws.Operation.perform/2
iex(2)> ExAws.RDS.describe_db_instances |> ExAws.request
** (Protocol.UndefinedError) protocol ExAws.Operation not implemented for %ExAws.Operation.RestQuery{http_method: :get, params: %{"Action" => "DescribeDBInstances", "Version" => "2014-10-31"}, path: "/", service: :rds}
    (ex_aws) lib/ex_aws/operation.ex:1: ExAws.Operation.impl_for!/1
    (ex_aws) lib/ex_aws/operation.ex:2: ExAws.Operation.perform/2
```

I'm trying to create an impl of `Operation` for `RestQuery`. Not sure that's the way forward with this but at least I get different errors now 😄

**Comment by gaustin** [comment]
I got something to work for my simple use-case:
```elixir
defimpl ExAws.Operation, for: ExAws.Operation.RestQuery do
  def perform(operation, config) do
    query =
      operation.params
      |> URI.encode_query

    ExAws.Request.request(operation.http_method, url(config, operation.path), query, [], config, operation.service)
  end

  def stream!(_, _), do: nil

  def url(%{scheme: scheme, host: host, port: port}, queue_name) do
    [
      scheme,
      host,
      port |> port(),
      queue_name
    ] |> IO.iodata_to_binary
  end

  defp port(80), do: ""
  defp port(p),  do: ":#{p}"
end
```

**Comment by benwilson512** [comment]
Hey, this is a definite oversight on my part. Will get a fix pushed to master here in a bit.

**Comment by gaustin** [comment]
Awesome. Thanks!
