### ISSUE TITLE
Troubles with uploading binary files via arc

### ISSUE THREAD

**Issue by TakteS** [CargoSense/ex_aws#271]
Hello. I use latest versions of ex_aws and arc for uploading files to S3. I try to upload files from a binary, like this:

```
# photos is a list of binaries
photos = photos |> Enum.map(&(%{filename: "photo.png", binary: &1 |> Base.decode64!}))

for photo <- photos do
  changeset = Photo.Validator.changeset(%Photo{}, %{property_id: property.id, photo: photo})
  if changeset.valid?, do: changeset |> Repo.insert
end
```

When I use arc Locale storage it works as well, but when I try to upload to the S3 bucket I got an error:

```
[error] Task #PID<0.673.0> started from #PID<0.663.0> terminating
** (MatchError) no match of right hand side value: %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<InitiateMultipartUploadResult xmlns=\"http:
//s3.amazonaws.com/doc/2006-03-01/\"><Bucket>ave88-test</Bucket><Key>uploads/properties/665/47e081b4-6af9-4b90-b2ca-dbe5652786af/large.png</Key><Upl
oadId>...--</UploadId></InitiateMultipartUploadResult>", headers:
 [{"x-amz-id-2", "..."}, {"x-amz-request-id", "..."}, {"Date", "Thu, 20 Oc
t 2016 09:35:06 GMT"}, {"Transfer-Encoding", "chunked"}, {"Server", "AmazonS3"}], status_code: 200}
    (ex_aws) lib/ex_aws/s3/upload.ex:39: ExAws.S3.Upload.initialize!/2
    (ex_aws) lib/ex_aws/s3/upload.ex:80: ExAws.Operation.ExAws.S3.Upload.perform/2
    (arc) lib/arc/storage/s3.ex:53: Arc.Storage.S3.do_put/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5

    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.113666932/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
```

Original photo was saved, but another versions (medium.png etc) aren't uploaded. 

It is a ex_aws trouble or arc? (I created issue about this on arc repo too). 

Thank you!

**Comment by benwilson512** [comment]
Please don't create an issue in both locations, it makes keeping track of the discussion very hard. Discussion should happen on `Arc` until we have a clear ExAws error.
