### ISSUE TITLE
301 permanent redirect when accessing a newly created S3 bucket.

### ISSUE THREAD

**Issue by jamesotron** [CargoSense/ex_aws#279]
Hi there.

I started working on features requiring S3 today in an app I'm building, so I added `ex_aws` `10.0.-rc.4` but I'm getting errors when trying to do anything (list objects, delete, etc) with a newly created bucket:

```
iex(1)> bucket_name = "test.example.demo.wat"
"test.example.demo.wat"
iex(2)> bucket_name |> ExAws.S3.put_bucket("ap-southeast-2") |> ExAws.request!
%{body: "",
  headers: [{"x-amz-id-2", "REDACTED"},
   {"x-amz-request-id", "REDACTED"},
   {"Date", "Fri, 04 Nov 2016 02:24:05 GMT"},
   {"Location", "http://test.example.demo.wat.s3.amazonaws.com/"},
   {"Content-Length", "0"}, {"Server", "AmazonS3"}], status_code: 200}
iex(3)> bucket_name |> ExAws.S3.delete_bucket |> ExAws.request!
** (CaseClauseError) no case clause matching: {:ok, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>test.example.demo.wat</Bucket><Endpoint>test.example.demo.wat.s3.amazonaws.com</Endpoint><RequestId>REDACTED</RequestId><HostId>REDACTED</HostId></Error>", headers: [{"x-amz-request-id", "REDACTED"}, {"x-amz-id-2", "REDACTED"}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Fri, 04 Nov 2016 02:24:19 GMT"}, {"Server", "AmazonS3"}], status_code: 301}}
    (ex_aws) lib/ex_aws/request.ex:34: ExAws.Request.request_and_retry/7
    (ex_aws) lib/ex_aws/operation/s3.ex:44: ExAws.Operation.ExAws.Operation.S3.perform/2
    (ex_aws) lib/ex_aws.ex:41: ExAws.request!/2
```

**Comment by benwilson512** [comment]
You likely haven't configured the region used by ExAws to be `ap-southeast-2`.

```
# in your mix config.
config :ex_aws
  region: "ap-southeast-2"
```
