### ISSUE TITLE
deploy: module Experimental.Flow is not available

### ISSUE THREAD

**Issue by mvalitov** [CargoSense/ex_aws#283]
my application uses ex_aws, and works fine in dev mode. But after deploy, in production mode, I get this error:
```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Experimental.Flow.from_enumerable/2 is undefined (module Experimental.Flow is not available)
        Experimental.Flow.from_enumerable(#Stream<[enum: %File.Stream{line_or_bytes: 5242880, modes: [:raw, :read_ahead, :raw, {:read_ahead, 65536}, :binary, :binary], path: "/tmp/plug-1478/multipart-961356-375861-1", raw: true}, funs: [#Function<62.89908360/1 in Stream.with_index/2>]]>, [stages: 4, max_demand: 2])
        (ex_aws) lib/ex_aws/s3/upload.ex:86: ExAws.Operation.ExAws.S3.Upload.perform/2
        (ex_aws) lib/ex_aws.ex:41: ExAws.request!/2
        (myapp) web/models/resource.ex:69: Myapp.Resource.put_file_to_cloud/1
        (myapp) web/controllers/resource_controller.ex:100: Myapp.ResourceController.upload/2
        (myapp) web/controllers/resource_controller.ex:1: Myapp.ResourceController.action/2
        (myapp) web/controllers/resource_controller.ex:1: Myapp.ResourceController.phoenix_controller_pipeline/2
        (myapp) lib/myapp/endpoint.ex:1: Myapp.Endpoint.instrument/4
iex(myapp@127.0.0.1)1>
```
I need to add the module Experimental in deps? If so, how does it work in the dev mode? thanks for any help

**Comment by benwilson512** [comment]
You need to add `:gen_stage` to the applications list.
