### ISSUE TITLE
Error parsing access keys?

### ISSUE THREAD

**Issue by joshuaswilcox** [CargoSense/ex_aws#291]
I am getting a random Unexpected token, has anyone else run into this?  Both `access_key_id` and `AWS_SECRET_ACCESS_KEY` are both set.  Running in non-prod works fine as well
```
%{image: %Plug.Upload{content_type: "image/jpeg",
   filename: "chalfonte_vsop.jpg",
   path: "/tmp/plug-1480/multipart-2593-764936-2"}}
[error] GenServer ExAws.Config.AuthCache terminating
** (Poison.SyntaxError) Unexpected token: n
    (poison) lib/poison/parser.ex:56: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    (ex_aws) lib/ex_aws/instance_meta.ex:23: ExAws.InstanceMeta.security_credentials/1
    (ex_aws) lib/ex_aws/config/auth_cache.ex:37: ExAws.Config.AuthCache.refresh_config/2
    (ex_aws) lib/ex_aws/config/auth_cache.ex:27: ExAws.Config.AuthCache.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by joshuaswilcox** [comment]
also this if that helps
```
Last message: {:refresh_config, %{access_key_id: "REDACTED", host: %{"ap-northeast-1" => "s3-ap-northeast-1.amazonaws.com", "ap-southeast-1" => "s3-ap-southeast-1.amazonaws.com", "ap-southeast-2" => "s3-ap-southeast-2.amazonaws.com", "eu-central-1" => "s3-eu-central-1.amazonaws.com", "eu-west-1" => "s3-eu-west-1.amazonaws.com", "sa-east-1" => "s3-sa-east-1.amazonaws.com", "us-east-1" => "s3.amazonaws.com", "us-west-1" => "s3-us-west-1.amazonaws.com", "us-west-2" => "s3-us-west-2.amazonaws.com"}, http_client: ExAws.Request.Hackney, json_codec: Poison, region: "us-east-1", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "https://", secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]}}
State: ExAws.Config.AuthCache
```

**Comment by benwilson512** [comment]
So based on the stack trace it's trying to use the AWS instance role, not the keys you have provided. Can you gist your config.exs and prod.exs ex_aws config?

**Comment by joshuaswilcox** [comment]
Yeah, so I guess I had the security wrong on s3 as well as a typo in my export of the secret, :(.  Its all working now.

**Comment by benwilson512** [comment]
Excellent, glad to hear it!
