### ISSUE TITLE
Long running SQS "** Too many db tables **"

### ISSUE THREAD

**Issue by mpneuried** [CargoSense/ex_aws#326]
After 22h of production use of your SQS solution i got an error:

```
** (SystemLimitError) a system limit has been reached
    (stdlib) :ets.new(:rules, [:set, :public])
    (xmerl) xmerl_scan.erl:418: :xmerl_scan.initial_state/2
    (xmerl) xmerl_scan.erl:300: :xmerl_scan.int_string/4
    (xmerl) xmerl_scan.erl:291: :xmerl_scan.string/2
    (sweet_xml) lib/sweet_xml.ex:233: SweetXml.parse/2
    (sweet_xml) lib/sweet_xml.ex:421: SweetXml.xpath/2
    (sweet_xml) lib/sweet_xml.ex:454: SweetXml.xpath/3
    (ex_aws) lib/ex_aws/sqs/parsers.ex:99: ExAws.SQS.Parsers.parse/2
10:22:19.693 [error] ** Too many db tables **
```

See: https://github.com/awetzel/sweet_xml/issues/41

**Comment by benwilson512** [comment]
Can you talk about your SQS usage a bit? Are you communicating with SQS in a highly concurrent way? Apparently xmerl creates :ets tables for scanning and either you're more concurrent SQS parse requests than there are allowable :ets tables (which we can fix just by upping the max table limit) or somehow xmerl is leaking tables.

**Comment by mpneuried** [comment]
I'm using it for a customer project and it is used inside one app of a bigger umbrella project.

In general i do a `SQS.receive_message` and until the processing is done i start a new receive.

## AWS-SQS

The queue is configured like this:
![bildschirmfoto 2017-01-13 um 06 42 06](https://cloud.githubusercontent.com/assets/300631/21919564/92e782a4-d95b-11e6-9fa5-359c5b2382b3.png)
So it should use the longpolling feature.

Here's a cloudwatch view of the outage for this queue:
![bildschirmfoto 2017-01-13 um 06 52 59](https://cloud.githubusercontent.com/assets/300631/21919747/2290c158-d95d-11e6-8b58-6d19f1ad99ad.png)

## CODE

Here's an extract of the relevant code fragments, that communicate with SQS:

**datasync.ex (main):**
```ex
defmodule Datasync do

	alias Datasync.Worker

# ...

	def start_link( ) do

		# ...

		import Supervisor.Spec
		
		children = [
			# Start the endpoint when the application starts
			worker( Worker, [ { qeue_name( ), queue_url( ) } ] )
		]
		
		opts = [ strategy: :one_for_one, name: Datasync.Supervisor ]
		Supervisor.start_link( children, opts )
	end
	
# ...

end
```

**datasync/worker.ex:**
```ex
defmodule Datasync.Worker do
	
	use GenServer
	require Logger
	
	alias Datasync.Messages
	
	def receive do
		GenServer.cast( __MODULE__, { :receive } )
	end

	def process( msg ) do
		# here messages will be processed  ...
	end
	
# ...

	# GENSERVER API
	def start_link( { queue, queue_url } ) do
		GenServer.start_link( __MODULE__, { queue, queue_url }, name: __MODULE__ )
	end
	
	def init( { queue, queue_url } ) do
		# start receiving messages
		receive( )
		
		{ :ok, { queue, queue_url } }
	end
	
	def handle_cast( { :receive }, { queue, queue_url } ) do

		process_receive(
			Messages.receive( [
				max_number_of_messages: 10,
				visibility_timeout: @visibility_timeout,
				wait_time_seconds: @wait_time_seconds,
				attribute_names: [
					:ApproximateReceiveCount,
					:ApproximateFirstReceiveTimestamp,
					:SentTimestamp
					]
			], queue )
		)
		
		# rerun receive to keep the worker running
		receive( )
		
		{ :noreply, { queue, queue_url } }
	end
	
	defp process_receive( { :ok, [ ] } ), do: Logger.debug "Datasync.Worker: got empty reply"
	
	defp process_receive( { :ok, messages } ) do
		Logger.debug "Datasync.Worker: got `#{ Enum.count( messages ) }` messages"
		for msg <- messages do
			process( msg )
		end
	end
	
	defp process_receive( { :error, error } ) do
		Logger.error( "Datasync.Worker: Error receive messeages - #{ error }" )
	end
	
	defp process_receive( _ ) do
		Logger.error( "Datasync.Worker: Unkown return" )
	end
	
# ...

end
```

**datasync/messages.ex:**
```ex
defmodule Datasync.Worker do

	
	alias ExAws.SQS, as: SQS
	alias Datasync.Handler
# ...

	def receive( opts \\ [ ], qname \\ @queuename ) do
		SQS.receive_message( qname, opts )
			|> ExAws.request
			|> Handler.handle( :receive_message )
	end
	
# ...

end
```


**datasync/handler.ex:**
```ex
defmodule Datasync.Handler do

# ...

	def handle( { :ok, %{ body: %{ messages: messages } } }, :receive_message ) do
		{ :ok, messages }
	end
	
# ...

end
```

**Comment by benwilson512** [comment]
Interesting. I will look into why it's holding onto tables. In the mean time you should be able to do a work around by doing:
```
task = Task.async(fn ->
			Messages.receive( [
				max_number_of_messages: 10,
				visibility_timeout: @visibility_timeout,
				wait_time_seconds: @wait_time_seconds,
				attribute_names: [
					:ApproximateReceiveCount,
					:ApproximateFirstReceiveTimestamp,
					:SentTimestamp
					]
			], queue )
end)
Task.await(task, some_reasonable_timeout)
```

This will run each sweet_xml parse in its own process. :ets tables are tied to the process that creates them. Thus when the process quits, it will kill any attached :ets tables that are still alive.

**Comment by benwilson512** [comment]
Someone suggested another possibility: If you're creating`:ets` tables anywhere else and leaking them, eventually `:xmerl` will ask for a table and there won't be any more.

Basically even if this is an `:xmerl` issue, it definitely isn't an ExAws issue, so I'm gonna close this for now.

**Comment by safwanolaimat** [comment]
same error here : 
 ```(xmerl) xmerl_scan.erl:296: :xmerl_scan.int_string/3
   (xmerl) xmerl_scan.erl:291: :xmerl_scan.string/2
   (sweet_xml) lib/sweet_xml.ex:233: SweetXml.parse/2
   (sweet_xml) lib/sweet_xml.ex:421: SweetXml.xpath/2
   (sweet_xml) lib/sweet_xml.ex:454: SweetXml.xpath/3
   (ex_aws_sqs) lib/ex_aws/sqs/parsers.ex:99: ExAws.SQS.Parsers.parse/2
```

**Comment by benwilson512** [comment]
Hey @safwanolaimat this isn't actually the same error, I'd consider looking for help on the forums, slack or IRC.
