### ISSUE TITLE
S3 endpoint error after upgrading.

### ISSUE THREAD

**Issue by ospaarmann** [CargoSense/ex_aws#333]
After upgrading to 1.0.0 I receive this error when trying to upload a file to S3

```
[error] Task #PID<0.1070.0> started from #PID<0.1062.0> terminating
** (CaseClauseError) no case clause matching: {:ok, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>myapp-dev</Bucket><Endpoint>myapp-dev.s3.amazonaws.com</Endpoint><RequestId>2B29E724AC4C3370</RequestId><HostId>VNo5p6Zw1se6WIjWJ2h+nnHdZ7j+9g6iQqVugj8GgxyeaHcXB2fdKfacLBQsGMfvGV5EOeDS+zI=</HostId></Error>", headers: [{"x-amz-bucket-region", "eu-central-1"}, {"x-amz-request-id", "2B29E724AC4C3370"}, {"x-amz-id-2", "VNo5p6Zw1se6WIjWJ2h+nnHdZ7j+9g6iQqVugj8GgxyeaHcXB2fdKfacLBQsGMfvGV5EOeDS+zI="}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Tue, 17 Jan 2017 12:04:13 GMT"}, {"Server", "AmazonS3"}], status_code: 301}}
    (ex_aws) lib/ex_aws/request.ex:34: ExAws.Request.request_and_retry/7
    (ex_aws) lib/ex_aws/operation/s3.ex:44: ExAws.Operation.ExAws.Operation.S3.perform/2
    (ex_aws) lib/ex_aws.ex:41: ExAws.request!/2
    (ex_aws) lib/ex_aws/s3/upload.ex:41: ExAws.S3.Upload.initialize!/2
    (ex_aws) lib/ex_aws/s3/upload.ex:83: ExAws.Operation.ExAws.S3.Upload.perform/2
    (arc) lib/arc/storage/s3.ex:57: Arc.Storage.S3.do_put/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.10313571/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
```

As far as I understand this might happen if the region is not defined correctly. My config looks like this:

```
config :my_app, :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  s3: [region: "eu-central-1"]
```

But I also tried

```
config :my_app, :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region: "eu-central-1"
```

And 

```
config :my_app, :ex_aws,
  access_key_id: "AWS_ACCESS_KEY_ID",
  secret_access_key: "AWS_SECRET_ACCESS_KEY",
  s3: [region: "eu-central-1"]
```

I double-checked the region in the S3 console and it is the correct one. And when checking the error message the correct region is in the headers. I am stuck and would appreciate any help to resolve this.

**Comment by benwilson512** [comment]
Remove the :my_app from the config namespace, just config :ex_aws directly

**Comment by ospaarmann** [comment]
Thanks. But the problem persists - in a different form.

When changing the config to

```
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  s3: [region: "eu-central-1"]
```

I receive this error:


```
[error] Task #PID<0.1074.0> started from #PID<0.1066.0> terminating
** (stop) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "ACCESSKEYID"}, :instance_role], host: %{"ap-northeast-1" => "s3-ap-northeast-1.amazonaws.com", "ap-southeast-1" => "s3-ap-southeast-1.amazonaws.com", "ap-southeast-2" => "s3-ap-southeast-2.amazonaws.com", "eu-central-1" => "s3-eu-central-1.amazonaws.com", "eu-west-1" => "s3-eu-west-1.amazonaws.com", "sa-east-1" => "s3-sa-east-1.amazonaws.com", "us-east-1" => "s3.amazonaws.com", "us-west-1" => "s3-us-west-1.amazonaws.com", "us-west-2" => "s3-us-west-2.amazonaws.com"}, http_client: ExAws.Request.Hackney, json_codec: Poison, region: "eu-central-1", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "https://", secret_access_key: [{:system, "SECRETKEY"}, :instance_role]}}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:604: GenServer.call/3
    (ex_aws) lib/ex_aws/config.ex:66: ExAws.Config.retrieve_runtime_value/2
    (elixir) lib/stream.ex:490: anonymous fn/4 in Stream.map/2
    (elixir) lib/enum.ex:2843: Enumerable.List.reduce/3
    (elixir) lib/stream.ex:1284: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:839: Enum.find/3
    (ex_aws) lib/ex_aws/config.ex:54: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1
    (stdlib) lists.erl:1263: :lists.foldl/3
    (ex_aws) lib/ex_aws/config.ex:30: ExAws.Config.new/2
    (ex_aws) lib/ex_aws.ex:29: ExAws.request/2
    (arc) lib/arc/storage/s3.ex:57: Arc.Storage.S3.do_put/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.10313571/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
[error] Ranch protocol #PID<0.1066.0> (:cowboy_protocol) of listener MyApp.Endpoint.HTTP terminated
** (exit) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "ACCESSKEYID"}, :instance_role], host: %{"ap-northeast-1" => "s3-ap-northeast-1.amazonaws.com", "ap-southeast-1" => "s3-ap-southeast-1.amazonaws.com", "ap-southeast-2" => "s3-ap-southeast-2.amazonaws.com", "eu-central-1" => "s3-eu-central-1.amazonaws.com", "eu-west-1" => "s3-eu-west-1.amazonaws.com", "sa-east-1" => "s3-sa-east-1.amazonaws.com", "us-east-1" => "s3.amazonaws.com", "us-west-1" => "s3-us-west-1.amazonaws.com", "us-west-2" => "s3-us-west-2.amazonaws.com"}, http_client: ExAws.Request.Hackney, json_codec: Poison, region: "eu-central-1", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "https://", secret_access_key: [{:system, "SECRETKEY"}, :instance_role]}}, 5000)
    ** (EXIT) time out
[error] GenServer ExAws.Config.AuthCache terminating
** (CaseClauseError) no case clause matching: {:error, %{reason: :connect_timeout}}
    (ex_aws) lib/ex_aws/instance_meta.ex:16: ExAws.InstanceMeta.request/2
    (ex_aws) lib/ex_aws/instance_meta.ex:34: ExAws.InstanceMeta.instance_role_credentials/1
    (ex_aws) lib/ex_aws/instance_meta.ex:40: ExAws.InstanceMeta.security_credentials/1
    (ex_aws) lib/ex_aws/config/auth_cache.ex:58: ExAws.Config.AuthCache.refresh_config/2
    (ex_aws) lib/ex_aws/config/auth_cache.ex:33: ExAws.Config.AuthCache.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:refresh_config, %{access_key_id: [{:system, "ACCESSKEYID"}, :instance_role], host: %{"ap-northeast-1" => "s3-ap-northeast-1.amazonaws.com", "ap-southeast-1" => "s3-ap-southeast-1.amazonaws.com", "ap-southeast-2" => "s3-ap-southeast-2.amazonaws.com", "eu-central-1" => "s3-eu-central-1.amazonaws.com", "eu-west-1" => "s3-eu-west-1.amazonaws.com", "sa-east-1" => "s3-sa-east-1.amazonaws.com", "us-east-1" => "s3.amazonaws.com", "us-west-1" => "s3-us-west-1.amazonaws.com", "us-west-2" => "s3-us-west-2.amazonaws.com"}, http_client: ExAws.Request.Hackney, json_codec: Poison, region: "eu-central-1", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "https://", secret_access_key: [{:system, "SECRETKEY"}, :instance_role]}}
State: ExAws.Config.AuthCache
```

And when using this config:

```
config :ex_aws,
  access_key_id: "AWS_ACCESS_KEY_ID",
  secret_access_key: "AWS_SECRET_ACCESS_KEY",
  s3: [region: "eu-central-1"]
```

I receive this error

```

[error] #PID<0.1102.0> running MyApp.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /fileapi/v1/tmp-application-avatar
** (exit) exited in: Task.await(%Task{owner: #PID<0.1102.0>, pid: #PID<0.1107.0>, ref: #Reference<0.0.2.10416>}, 15000)
    ** (EXIT) time out
```

So it basically comes down to a time out now. Any idea why?

**Comment by benwilson512** [comment]
Well the second configuration option just says that your actual access key id is literally `"AWS_ACCESS_KEY_ID"` which is not the case. The `{:system` version was correct but the timeout happened because `System.get_env("AWS_ACCESS_KEY_ID")` returned nil and so it tried to use the instance role meta option. This however is only available on actual AWS instances, so it times out if you try to run it locally.

**Comment by ospaarmann** [comment]
Ah, ok, so I always have to get the access keys from the env variables? This would be bad since I have some issues with env variables when deploying to production on Docker. Right now I have the keys in prod.secret.exs. I know this is not ideal, but for me atm the only viable solution.

**Comment by benwilson512** [comment]
You do not have to always use environment variables no. In your prod.secret.exs you could have the literal values of the environment variables hard coded in as `access_key_id: "asdf8asfd9sdf8sdf7"`.

**Comment by ospaarmann** [comment]
Thank you for your help. But now I still receive this timeout:

```
[error] #PID<0.1102.0> running MyApp.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /fileapi/v1/tmp-application-avatar
** (exit) exited in: Task.await(%Task{owner: #PID<0.1102.0>, pid: #PID<0.1107.0>, ref: #Reference<0.0.2.10416>}, 15000)
    ** (EXIT) time out
```

**Comment by benwilson512** [comment]
That looks like an error in  your code. At least, there's nothing in that stack trace that references ExAws.

**Comment by ospaarmann** [comment]
The problem was with the S3 region and ex_aws. The configuration isn't deep merged which leads to the code to silently fail. The solution was to add the whole s3 configuration to config.exs:

```
config :ex_aws, :s3,
  scheme: "https://",
  host: "s3.eu-central-1.amazonaws.com",
  region: "eu-central-1"
```

You can find the correct host for your region [here](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region). The issue that helped me solve this can be found [here](https://github.com/CargoSense/ex_aws/issues/103). 

Hope that helps someone.

**Comment by benwilson512** [comment]
You should be able to add the whole the `region: "eu-central-1"` directly to the `config :ex_aws` stuff without nesting it under s3, and then you can leave out the whole host and scheme bit. IE your whole config would be:
```
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region: "eu-central-1"
```

**Comment by ospaarmann** [comment]
Thanks. And well, I still receive a time out error. I'm using ex_aws together with arc / arc_ecto and I could narrow it down to 

`cast_attachments(params, [:avatar])`

which takes forever and then fails. So I guess I ask over at the arc repo...

**Comment by ijunaid8989** [comment]
> The problem was with the S3 region and ex_aws. The configuration isn't deep merged which leads to the code to silently fail. The solution was to add the whole s3 configuration to config.exs:
> 
> ```
> config :ex_aws, :s3,
>   scheme: "https://",
>   host: "s3.eu-central-1.amazonaws.com",
>   region: "eu-central-1"
> ```
> 
> You can find the correct host for your region [here](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region). The issue that helped me solve this can be found [here](https://github.com/CargoSense/ex_aws/issues/103).
> 
> Hope that helps someone.

can we also put a port value here? I mean do aws s3 endpoint also has a default port to which It sends the request

**Comment by benwilson512** [comment]
@ijunaid8989 please do not use the issue trackers for questions, instead use the elixir forum, slack, or other resources.
