### ISSUE TITLE
Whether request or request!, when download fails it makes no difference

### ISSUE THREAD

**Issue by cvarona** [CargoSense/ex_aws#346]
Hi,
when I use S3 to download an existing object, like this:
```
iex(1)> alias ExAws.S3
ExAws.S3
iex(2)> {a,b}=S3.download_file("one_bucket_of_mine", "existing_object_path, "/home/me/some_path_to_file")|> ExAws.request
{:ok, :done}
iex(3)> S3.download_file("one_bucket_of_mine", "existing_object_path, "/home/me/some_path_to_file")|> ExAws.request!      
:done
```
everything goes ok. However, if I try to download a non-existing object, like this:
```
iex(4)> {a,b}=S3.download_file("one_bucket_of_mine", "non_existing_object_path, "/home/me/some_path_to_file")|> ExAws.request
** (ExAws.Error) ExAws Request Error!

{:error, {:http_error, 404, %{headers: [{"x-amz-request-id", "BEBD45BA6296FD80"}, {"x-amz-id-2", "l7Wi0psmUCcr2wydutP5SybfqB7Kk0rKHTow1wpOuF7Ffmju65BLdpWv9r2ltbf4wNWgzIqVjIk="}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Fri, 27 Jan 2017 09:50:00 GMT"}, {"Server", "AmazonS3"}], status_code: 404}}}

    (ex_aws) lib/ex_aws.ex:46: ExAws.request!/2
    (ex_aws) lib/ex_aws/s3/download.ex:52: ExAws.S3.Download.get_file_size/3
    (ex_aws) lib/ex_aws/s3/download.ex:29: ExAws.S3.Download.build_chunk_stream/2
    (ex_aws) lib/ex_aws/s3/download.ex:69: ExAws.Operation.ExAws.S3.Download.perform/2
iex(4)> S3.download_file("one_bucket_of_mine", "non_existing_object_path, "/home/me/some_path_to_file")|> ExAws.request!      
** (ExAws.Error) ExAws Request Error!

{:error, {:http_error, 404, %{headers: [{"x-amz-request-id", "9179632BB1955407"}, {"x-amz-id-2", "3ppWNE1zUm89OyZVIWaOb/Iqkt5Ss+9oNg/WFVvFwk+RofHf4H7z0EtJAIAl7qd+TLq9OtkKnnc="}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Fri, 27 Jan 2017 09:50:10 GMT"}, {"Server", "AmazonS3"}], status_code: 404}}}

    (ex_aws) lib/ex_aws.ex:46: ExAws.request!/2
    (ex_aws) lib/ex_aws/s3/download.ex:52: ExAws.S3.Download.get_file_size/3
    (ex_aws) lib/ex_aws/s3/download.ex:29: ExAws.S3.Download.build_chunk_stream/2
    (ex_aws) lib/ex_aws/s3/download.ex:69: ExAws.Operation.ExAws.S3.Download.perform/2
    (ex_aws) lib/ex_aws.ex:41: ExAws.request!/2
```
an error is raised, regardless of whether request or request! is used. If I've understood correctly what the documentation says, the former should yield {:error, reason} rather than exhibit the same behaviour as its ! counterpart, isn't it?

Regards

**Comment by benwilson512** [comment]
Yup yeah this is a bug. I made the fix for `S3.upload` but forgot for download. Will fix.

**Comment by marramgrass** [comment]
@benwilson512 I needed to fix this quickly for a project I'm working on; our fork is from before the move to `Task.async_stream`, but if you haven't got to it yet do you want me to update it accordingly and submit a PR here?

My diff is at https://github.com/GoReport/ex_aws/pull/2/files

**Comment by benwilson512** [comment]
Gonna close this, ultimately I don't think this is an ExAws issue.
