### ISSUE TITLE
Error trying to connect to AWS

### ISSUE THREAD

**Issue by tqpham** [CargoSense/ex_aws#373]
Hello! I'm new to Elixir and trying to get a connection to AWS. I've setup AWS S3 and able to connect to it other environments, so I believe my credentials are good. However, I'm unable to connect here. The changes to mix.exs and config.exs are as follows:
```
#mix.exs
  def application do
    [applications: [:ex_aws, :hackney, :poison]]
    [extra_applications: [:logger]]
  end
  defp deps do
    [
      {:ex_aws, "~> 1.1"},
      {:poison, "~> 2.0"},
      {:hackney, "~> 1.6"}
    ]
  end
#config.exs
  config :myapp, :ex_aws,
    access_key_id: [{:system, "xxxxxxx"}, :instance_role],
    secret_access_key: [{:system, "xxxxxxx"}, :instance_role],
    region: "us-west-2"
```
The following error shows. Also, not sure why it is picking up 'AWS_ACCESS_KEY_ID' when i've specified it in config. Error indicates may be environment variables, but not sure where/how it needs to be set. Thanks for any assistance!
```
** (exit) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role], host: %{"ap-northeast-1" => "s3-ap-northeast-1.amazonaws.com", "ap-northeast-2" => "s3-ap-northeast-2.amazonaws.com", "ap-south-1" => "s3-ap-south-1.amazonaws.com", "ap-southeast-1" => "s3-ap-southeast-1.amazonaws.com", "ap-southeast-2" => "s3-ap-southeast-2.amazonaws.com", "ca-central-1" => "s3-ca-central-1.amazonaws.com", "eu-central-1" => "s3-eu-central-1.amazonaws.com", "eu-west-1" => "s3-eu-west-1.amazonaws.com", "eu-west-2" => "s3-eu-west-2.amazonaws.com", "sa-east-1" => "s3-sa-east-1.amazonaws.com", "us-east-1" => "s3.amazonaws.com", "us-west-1" => "s3-us-west-1.amazonaws.com", "us-west-2" => "s3-us-west-2.amazonaws.com"}, http_client: ExAws.Request.Hackney, json_codec: Poison, region: "us-east-1", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "https://", secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]}}, 30000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:737: GenServer.call/3
    (ex_aws) lib/ex_aws/config.ex:66: ExAws.Config.retrieve_runtime_value/2
    (elixir) lib/stream.ex:495: anonymous fn/4 in Stream.map/2
    (elixir) lib/enum.ex:3080: Enumerable.List.reduce/3
    (elixir) lib/stream.ex:1403: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:868: Enum.find/3
    (ex_aws) lib/ex_aws/config.ex:54: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1
    (stdlib) lists.erl:1263: :lists.foldl/3
iex(2)> 
16:43:00.772 [error] GenServer ExAws.Config.AuthCache terminating
** (RuntimeError) Instance Meta Error: {:error, %{reason: :timeout}}

You tried to access the AWS EC2 instance meta, but it could not be reached.
This happens most often when trying to access it from your local computer,
which happens when environment variables are not set correctly prompting
ExAws to fallback to the Instance Meta.

Please check your key config and make sure they're configured correctly:

For Example:

ExAws.Config.new(:s3)
ExAws.Config.new(:dynamodb)

    (ex_aws) lib/ex_aws/instance_meta.ex:20: ExAws.InstanceMeta.request/2
    (ex_aws) lib/ex_aws/instance_meta.ex:52: ExAws.InstanceMeta.instance_role_credentials/1
    (ex_aws) lib/ex_aws/instance_meta.ex:58: ExAws.InstanceMeta.security_credentials/1
    (ex_aws) lib/ex_aws/config/auth_cache.ex:58: ExAws.Config.AuthCache.refresh_config/2
    (ex_aws) lib/ex_aws/config/auth_cache.ex:33: ExAws.Config.AuthCache.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:refresh_config, %{access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role], host: %{"ap-northeast-1" => "s3-ap-northeast-1.amazonaws.com", "ap-northeast-2" => "s3-ap-northeast-2.amazonaws.com", "ap-south-1" => "s3-ap-south-1.amazonaws.com", "ap-southeast-1" => "s3-ap-southeast-1.amazonaws.com", "ap-southeast-2" => "s3-ap-southeast-2.amazonaws.com", "ca-central-1" => "s3-ca-central-1.amazonaws.com", "eu-central-1" => "s3-eu-central-1.amazonaws.com", "eu-west-1" => "s3-eu-west-1.amazonaws.com", "eu-west-2" => "s3-eu-west-2.amazonaws.com", "sa-east-1" => "s3-sa-east-1.amazonaws.com", "us-east-1" => "s3.amazonaws.com", "us-west-1" => "s3-us-west-1.amazonaws.com", "us-west-2" => "s3-us-west-2.amazonaws.com"}, http_client: ExAws.Request.Hackney, json_codec: Poison, region: "us-east-1", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "https://", secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]}}
State: ExAws.Config.AuthCache

```

**Comment by benwilson512** [comment]
You may have read outdated docs, the config is not namespaced under your app anymore.

You should just do
```
  config :ex_aws,
    access_key_id: [{:system, "xxxxxxx"}, :instance_role],
    secret_access_key: [{:system, "xxxxxxx"}, :instance_role],
    region: "us-west-2"
```

**Comment by tqpham** [comment]
Removing app name doesn't seem to make a difference. I've even exited iex and restarted, iex -S mix. However, it does now show my access_key_id/secret_access_key in the error log.

**Comment by benwilson512** [comment]
Does
```
ExAws.Config.new(:s3)
```

**Comment by tqpham** [comment]
I've tried that in my method before and it gives the same error. Not exactly sure where it should go, but I placed in config.exs and also called it from command line, same error.

**Comment by benwilson512** [comment]
Er so question, why are you striking out "xxxx" from the {:system, "xxxxxxx"}? That should't have your key, it should have the environment variable that you're using, which isn't a secret.

**Comment by tqpham** [comment]
I guess I need to research how to setup the environment variable. thanks for your time.
