### ISSUE TITLE
upload errors

### ISSUE THREAD

**Issue by dfcarpenter** [CargoSense/ex_aws#390]
So i've been trying to understand why my uploads keep erroring. 

`````
config :ex_aws,
  access_key_id: <redacted>, # using hardcoded strings for this and access key
  secret_access_key: <redacted>,
  http_client: ExAws.Request.Hackney,
  host: "s3.amazonaws.com",
  json_codec: Poison,
  region: "us-west-1",
  port: 443

config :ex_aws, :s3,
  scheme: "https://",
  host: "s3.us-west-1.amazonaws.com",
  region: "us-west-1"
  
My function
def s3upload(file_path, extension, hash) do
		 IO.inspect ExAws.Config.new(:s3)

		 ExAws.S3.put_object("mybucket", "uploads/#{hash}#{extension}", File.read!(file_path))
  		 |> ExAws.request!
	 	
	end

Error (bucket does in fact exist and config shows the correct output)

** (exit) an exception was raised:
    ** (ExAws.Error) ExAws Request Error!

{:error, {:http_error, 404, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>s3.us-west-1.amazonaws.com</BucketName><RequestId>CC237BF68A97D4E3</RequestId><HostId>fNT+Lznf7XafUe2tru1CVExGekR9Hom4i5Y5DP3iBpk4YQmcAhhGBrotEbYxk5Q2j8nCw7GFu0E=</HostId></Error>", headers: [{"x-amz-request-id", "CC237BF68A97D4E3"}, {"x-amz-id-2", "fNT+Lznf7XafUe2tru1CVExGekR9Hom4i5Y5DP3iBpk4YQmcAhhGBrotEbYxk5Q2j8nCw7GFu0E="}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Sat, 25 Mar 2017 20:03:45 GMT"}, {"Connection", "close"}, {"Server", "AmazonS3"}], status_code: 404}}}

        (ex_aws) lib/ex_aws.ex:46: ExAws.request!/2
        (api) lib/api/uploads.ex:8: API.Uploads.create/1
        (portal) lib/portal/web/controllers/upload_controller.ex:1: Portal.Web.UploadController.action/2
        (portal) lib/portal/web/controllers/upload_controller.ex:1: Portal.Web.UploadController.phoenix_controller_pipeline/2
        (portal) lib/portal/web/endpoint.ex:12: Portal.Web.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:277: Phoenix.Router.__call__/1
        (portal) lib/portal/web/endpoint.ex:12: Portal.Web.Endpoint.plug_builder_call/2
        (portal) lib/plug/debugger.ex:123: Portal.Web.Endpoint."call (overridable 3)"/2
        (portal) lib/portal/web/endpoint.ex:12: Portal.Web.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/dan/work/iot_portal/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
````

**Comment by dfcarpenter** [comment]
Actually this problem was getting caused by my admin forcing MFA which had a policy that restricted access to any resource unless the user was MFA’ed into the service trumping all other policies.
