### ISSUE TITLE
ExAws.Request.Url build.2 fails when passed a string for port

### ISSUE THREAD

**Issue by AlexMouton** [CargoSense/ex_aws#409]
Hi

iex(12)> ExAws.Request.Url.build(%{path: "/api"},%{scheme: "http", host: "localhost", port: "80"})
** (ArgumentError) argument error
             :erlang.integer_to_binary("80")
    (elixir) lib/uri.ex:556: String.Chars.URI.extract_authority/1
    (elixir) lib/uri.ex:537: String.Chars.URI.to_string/1
    (ex_aws) lib/ex_aws/request/url.ex:15: ExAws.Request.Url.build/2
iex(12)> ExAws.Request.Url.build(%{path: "/api"},%{scheme: "http", host: "localhost", port: 80})  
"http://localhost/api"

I am using :ex_aws, "1.1.2".
Excuse the rough request. I am new to elixir so still a little unsure on my feet. 
I made a local copy of convert_port_to_integer which seems to work:
iex(13)> Haha.convert_port_to_integer(%{port: "80"})                                              
%{port: 80}

Conversion to the URI struct happens without incident as you would expect. 
So I am unclear as to how the string port is coming through to URI.to_string.

Thanks
A

**Comment by AlexMouton** [comment]
Aha. #380 
Merged to master a whole month ago and not released??
