### ISSUE TITLE
Cannot get ExAws working ERTS20, E1.4.5, Win10 -  looking for assistance, tips?

### ISSUE THREAD

**Issue by harmon25** [CargoSense/ex_aws#454]
Trying to use ExAws for SES, and S3 Amazon services.

Am getting errors with both that I cannot seem to debug.

I have tested the applied policy with the policy validator and am pretty sure I have the correct permissions defined on the AWS/IAM side.

### For S3 - when attempting to list buckets receive the following error:
```
iex(1)> ExAws.S3.list_buckets() |> ExAws.request!
** (ExAws.Error) ExAws Request Error!

{:error, {:http_error, 400, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n
<Error>
<Code>InvalidBucketName</Code>
<Message>The specified bucket is not valid.</Message>
<BucketName>s3.amazonaws.com, s3.amazonaws.com</BucketName><RequestId>3BB5B49AECE4ADE0</RequestId>
<HostId>yJyLU8kDGBTtv14AEf9xepG65Xb0UBiczyJwgLlf+G+Yd4SHm8w3rWpsjoWcUUv4NRvbkRehdjo=</HostId>
</Error>", headers: [{"x-amz-request-id", "3BB5B49AECE4ADE0"}, {"x-amz-id-2", "xxxxxxxxxxxxxxxxxxxxxxx"}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Wed, 12 Jul 2017 19:03:41 GMT"}, {"Connection", "close"}, {"Server", "AmazonS3"}], status_code: 400}}}
```

It is using **s3.amazonaws.com, s3.amazonaws.com** as BucketName... that cannot be right?

Am getting the same error when running:
`ExAws.S3.list_objects("existing-bucket") |> ExAws.request!`

### For SES:
Was getting auth errors i could not seem to resolve.
Now since adding sweet_xml for S3, am getting a sweet xml error:

```
iex(1)>  msg = ExAws.SES.build_message("some html?", "txt", "sub")
iex(2)> dest = %{to: ["me@domain.com"]}
iex(3)> ExAws.SES.send_email(dest, msg, "app@domain.com") |> ExAws.request(region: "us-east-1")
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:116: Enumerable.reduce/3
       (elixir) lib/stream.ex:849: Stream.do_enum_transform/10
       (elixir) lib/stream.ex:785: Stream.do_transform/8
    (sweet_xml) lib/sweet_xml.ex:582: anonymous fn/4 in SweetXml.continuation_opts/2
        (xmerl) xmerl_scan.erl:568: :xmerl_scan.scan_document/2
        (xmerl) xmerl_scan.erl:291: :xmerl_scan.string/2
    (sweet_xml) lib/sweet_xml.ex:237: SweetXml.parse/2
    (sweet_xml) lib/sweet_xml.ex:421: SweetXml.xpath/2
    (sweet_xml) lib/sweet_xml.ex:531: anonymous fn/3 in SweetXml.xmap/3
       (elixir) lib/map.ex:694: Map.get_and_update/3
    (sweet_xml) lib/sweet_xml.ex:531: SweetXml.xmap/3
    (sweet_xml) lib/sweet_xml.ex:530: SweetXml.xmap/3
       (ex_aws) lib/ex_aws/ses/parsers.ex:83: ExAws.SES.Parsers.parse/2
```

Am using ERTS-20 and Elixir 1.4.5 on Windows 10.
Any help is appreciated!!

**Comment by harmon25** [comment]
It doesn't help that new hackney 1.8.6 gets errors on Windows 10, so have been using old hackney..
Need to test on linux to see if it is a Windows problem..

**Comment by harmon25** [comment]
yea some issue with Windows it appears, possible to do with hackney problems... worked first try on debian.

Not a problem with ExAws, more dependency and environment related
