### ISSUE TITLE
Can't create an S3 client module using `otp_app` option

### ISSUE THREAD

**Issue by myronmarston** [CargoSense/ex_aws#50]
Based on [these docs](http://hexdocs.pm/ex_aws/ExAws.S3.Client.html), I expected the following to work:

``` elixir
# lib/delorean/s3.ex
defmodule Delorean.S3 do
  use ExAws.S3.Client, opt_app: :delorean
end
```

``` elixir
# config/config.exs
use Mix.config

config :delorean, ExAws,
  s3: [region: "us-west-2", scheme: "https://", host: "s3.amazonaws.com"]

import_config "s3_creds.exs"
```

``` elixir
# config/s3_creds.exs
use Mix.Config

config :delorean, ExAws,
  access_key_id: "redacted",
  secret_access_key: "redacted"
```

However, I get an error:

```
     ** (RuntimeError) A valid configuration root is required in your s3 client
     stacktrace:
       (ex_aws) lib/ex_aws/config.ex:23: ExAws.Config.get/1
       (ex_aws) lib/ex_aws/config.ex:14: ExAws.Config.build/2
       (delorean) lib/delorean/s3.ex:2: Delorean.S3.list_objects!/2
 ```

I can get it to work by changing `lib/delorean/s3.ex` to:

``` elixir
defmodule Delorean.S3 do
  use ExAws.S3.Client

  def config_root do
    Application.get_all_env(:delorean)[ExAws]
  end
end
```

...but that doesn't seem necessary.  What am I doing wrong?  Or are your docs inaccurate?

**Comment by benwilson512** [comment]
I apologize that's an outdated error in the docs. In your config, do
```
config :delorean, :ex_aws, #note :ex_aws instead of ExAws
  access_key_id: "redacted",
  secret_access_key: "redacted"
```

This is so that it more naturally matches the base case of
```
config :ex_aws,
  #stuff
```

I will update the docs shortly.

**Comment by benwilson512** [comment]
Docs are updated.
