### ISSUE TITLE
Follow S3 redirects for regions

### ISSUE THREAD

**Issue by adbl** [CargoSense/ex_aws#71]
I can't get any request to bucket on regions other than "US Standard" to work.
```
iex(4)> ExAws.S3.list_objects "bucket"
Request URL: "https://bucket.s3.amazonaws.com/"
...
** (CaseClauseError) no case clause matching: {:ok, %HTTPoison.Response{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>TemporaryRedirect</Code><Message>Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.</Message><Bucket>bucket</Bucket><Endpoint>bucket.s3-eu-west-1.amazonaws.com</Endpoint><RequestId>...</RequestId><HostId>...</HostId></Error>", headers: [{"x-amz-bucket-region", "eu-west-1"}, {"x-amz-request-id", "..."}, {"x-amz-id-2", "..."}, {"Location", "https://shim-wtf.s3-us-west-2.amazonaws.com/"}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Tue, 08 Sep 2015 13:04:34 GMT"}, {"Server", "AmazonS3"}], status_code: 307}}
    (ex_aws) lib/ex_aws/request.ex:33: ExAws.Request.request_and_retry/7
    (ex_aws) lib/ex_aws/s3/impl.ex:52: ExAws.S3.Impl.list_objects/3
```

Configuring s3.region doesn't make any difference...

**Comment by benwilson512** [comment]
Can you show me your config.exs? I just set the following and had no issues querying a bucket in `us-west-2`

```elixir
config :ex_aws, :s3,
  scheme: "https://",
  host: "s3-us-west-2.amazonaws.com",
  region: "us-west-2"
```

**Comment by adbl** [comment]
Oh, `host: "s3-us-west-2.amazonaws.com"`, I missed that! 
I can't find that in the docs even now actually...

**Comment by adbl** [comment]
It works fine btw, thanks!
