### ISSUE TITLE
list_objects expects GetObjectAcl permission

### ISSUE THREAD

**Issue by adbl** [CargoSense/ex_aws#72]
Unless `s3:GetObjectAcl` action is allowed, the `Content` entries of the response xml will not contain this part, which seems to be expected by the parsing code:
```xml
<Owner><ID>...</ID><DisplayName>...</DisplayName></Owner>
```

leads to this crash:
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:112: Enumerable.reduce/3
    (elixir) lib/stream.ex:695: Stream.do_enum_transform/8
    (elixir) lib/stream.ex:647: Stream.do_transform/7
             lib/sweet_xml.ex:484: anonymous fn/4 in SweetXml.continuation_opts/2
             xmerl_scan.erl:565: :xmerl_scan.scan_document/2
             xmerl_scan.erl:288: :xmerl_scan.string/2
             lib/sweet_xml.ex:180: SweetXml.parse/2
```

**Comment by benwilson512** [comment]
Good catch, should have a fix up soon.

**Comment by benwilson512** [comment]
I have a PR up on SweetXml here: https://github.com/awetzel/sweet_xml/pull/10 that should fix this issue.

**Comment by JustMikey** [comment]
The PR has been merged. Has the issue been solved?

**Comment by benwilson512** [comment]
It should bed yup.
