### ISSUE TITLE
Dynamo.Encodable protocol not implemented

### ISSUE THREAD

**Issue by jordi-chacon** [CargoSense/ex_aws#82]
Hi Ben!

I am using version 0.4.8.

I am getting the following error when putting an item into Dynamo:
```
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol ExAws.Dynamo.Encodable not implemented for %Service.Operation{oid: "1442-696618-318045", type: "2"}
        (ex_aws) lib/ex_aws/dynamo/encodable.ex:1: ExAws.Dynamo.Encodable.impl_for!/1
        (ex_aws) lib/ex_aws/dynamo/encodable.ex:6: ExAws.Dynamo.Encodable.encode/1
        (ex_aws) lib/ex_aws/dynamo/impl.ex:147: ExAws.Dynamo.Impl.put_item/4
```

Since I have declared the Encodable protocol in the Operation module I am really confused by this error. Here is a simplified version of the Operation module, which still causes the exception:
```
defmodule Service.Operation do
  alias __MODULE__

  @derive [ExAws.Dynamo.Encodable]
  defstruct [:oid, :type]

  def setup_store do
    ExAws.Dynamo.create_table("Operations", "oid", %{oid: :string}, 1, 1)
  end

  def new(oid, _, _, _) do
    %Operation{type: "2",
               oid: oid
              }
  end

  def write(operation) do
    ExAws.Dynamo.put_item("Operations", operation)
  end
end
```

Obviously I must be doing something wrong but I honestly can't see it... I'd appreciate some help.

Thank you again Ben!

**Comment by jordi-chacon** [comment]
Running `make clean` and compiling again fixed it. Weird.
