### ISSUE TITLE
Exception on S3 delete_object

### ISSUE THREAD

**Issue by ericmj** [CargoSense/ex_aws#97]
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for "connection/1.0.2/css/elixir.css"
(elixir) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir) lib/enum.ex:112: Enumerable.reduce/3
(elixir) lib/enum.ex:1398: Enum.reduce/3
(ex_aws) lib/ex_aws/s3/impl.ex:201: ExAws.S3.Impl.delete_object/4
(ex_aws) lib/ex_aws/s3/impl.ex:204: ExAws.S3.Impl.delete_object!/4
(elixir) lib/enum.ex:585: anonymous fn/3 in Enum.each/2
(elixir) lib/enum.ex:1390: anonymous fn/3 in Enum.reduce/3
(elixir) lib/stream.ex:1220: anonymous fn/3 in Enumerable.Stream.reduce/3
(elixir) lib/enum.ex:2607: Enumerable.List.reduce/3
(elixir) lib/stream.ex:1119: Stream.do_list_resource/6
(elixir) lib/stream.ex:1240: Enumerable.Stream.do_each/4
(elixir) lib/enum.ex:1389: Enum.reduce/3
(elixir) lib/enum.ex:584: Enum.each/2
(hex_web) lib/hex_web/api/handlers/docs.ex:120: HexWeb.API.Handlers.Docs.upload_docs/3
(elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
(stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/
```

Happens on commit 649d36c9e26f3111fe03a6cef847af361f81dec6.

**Comment by ericmj** [comment]
Bug in user code.
